services:
  bot:
    build: .
    ports:
      - 443:443
      - 80:80
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=bot_user
    expose:
      - 5432
